#!/bin/bash
# Quick Start Guide Script

echo "=========================================="
echo "LipoAgent Quick Start Guide"
echo "=========================================="
echo ""
echo "This project has two main functions:"
echo ""
echo "1. FINETUNE TRAINING (Multi-Task Loss)"
echo "   Command: python multi_task_training.py"
echo "   Config:  training_config.yaml"
echo "   Output:  ./qwen_lora_finetuned_multi_task/"
echo ""
echo "2. MULTI-AGENT LOOP (Predictor + Verifier)"
echo "   Command: python multi_agent_pipeline.py"
echo "   Config:  config.yaml"
echo "   Output:  output/"
echo ""
echo "=========================================="
echo "Recommended Workflow:"
echo "=========================================="
echo ""
echo "Step 1: Prepare data (if needed)"
echo "  python process_toxicity_data.py"
echo ""
echo "Step 2: Finetune the model"
echo "  python multi_task_training.py"
echo ""
echo "Step 3: Run multi-agent prediction"
echo "  python multi_agent_pipeline.py"
echo ""
echo "=========================================="
echo "Verify code:"
echo "  python verify_code.py"
echo "=========================================="
